% 2016 03 25  Calculate pressure field

clear

mode_path = 'F:\Dropbox\0_APL_normal_mode\kraken\tests\wjlee_tests';
mode_file = 'trex13_2layers_5D_allModes_1901w.mod';

clear read_modes_bin % to force rewind to beginning of mode file

modes = read_modes(fullfile(mode_path,mode_file));
phi = get_component(modes,'N');

cw = 1525;
kr = modes.k;

r = 0:10:5000;  % distance [m]
z_calc = modes.z;     % depth [m]
delta_z = 0.1;  % depth spacing [m]
z = z_calc(1):delta_z:z_calc(end);
z0 = 17.8;       % source depth [m]

mode_incl = length(modes.k);
phi_incl = phi(:,1:mode_incl);

% interpolation on mode function
phi_z = interp1(z_calc,phi_incl,z);
phi_z0 = interp1(z_calc,phi_incl,z0);

kr_r = kr*r;
H = besselh(0,2,kr_r);

p = 1i*pi*repmat(phi_z0,size(phi_z,1),1).*phi_z *H(1:mode_incl,:);

p_abs = abs(p);
p_abs(p_abs<1e-7) = 1e-7;
p_abs(isnan(p_abs)) = 1e-6;
p_abs(isinf(p_abs)) = 1e-6;

% tl = -20*log10(abs(p));
tl = -20*log10(p_abs);

% % interpolation on resultant field
% phi_z = phi_incl;
% [~,z0_idx] = min(abs(z-z0));
% phi_z0 = phi_incl(z0_idx,:);
% 
% p2 = 1i*pi*repmat(phi_z0,size(phi_z,1),1).*phi_z *H(1:mode_incl,:);
% 
% [r2,z2] = meshgrid(r,z);
% [rq,zq] = meshgrid(r,zz);
% p2_interp_abs = griddata(r2,z2,double(abs(p2)),rq,zq);


% Load SHD file generated by Kraken
shd_file = regexprep(mode_file,'mod','shd');
[PlotTitle,~,freq,~,Pos,p_flp] = read_shd(shd_file);
p_flp = squeeze(p_flp(1,1,:,:));
z_flp = Pos.r.depth;
r_flp = Pos.r.range;

p_flp_abs = abs(p_flp);
p_flp_abs(p_flp_abs<1e-7) = 1e-7;
p_flp_abs(isnan(p_flp_abs)) = 1e-6;
p_flp_abs(isinf(p_flp_abs)) = 1e-6;

% tl_flp = -20*log10(abs(p_flp));
tl_flp = -20*log10(p_flp_abs);


% Save generated pressure field
save_file = strsplit(mode_file,'.');
save_matlab = [save_file{1},'_pfield_matlab.mat'];
save(fullfile(mode_path,save_matlab),'tl','z','r');
save_kraken = [save_file{1},'_pfield_kraken.mat'];
save(fullfile(mode_path,save_kraken),'tl_flp','z_flp','r_flp');


% Plot
figure
subplot(121)
imagesc(r,z,tl);
xlabel('Range (m)')
ylabel('Depth (m)')
colormap(fliplr(jet))
caxisrev([30 80])
title('Direct calculation in Matlab')

subplot(122)
imagesc(r_flp,z_flp,tl_flp);
xlabel('Range (m)')
ylabel('Depth (m)')
colormap(fliplr(jet))
caxisrev([30 80])
title('Kraken field calculation')